export const CHAT_ADD_NEW_MESSAGE = "CHAT/ADD_NEW_MESSAGE";
export const CHAT_CHANGE_MESSAGE_BODY = "CHAT/CHANGE_MESSAGE_BODY";
export const CHAT_RESET_MESSAGE_BODY = "CHAT/RESET_MESSAGE_BODY";
export const CHAT_CHANGE_ACTIVE_PANEL = "CHAT/CHANGE_ACTIVE_PANEL";

export const USERS_CHANGE_FOLLOWING_USER = "USERS/CHANGE_FOLLOWING_USER";
export const USERS_CHANGE_FIND_USER_BODY = "USERS/CHANGE_FIND_USER_BODY";
export const USERS_RESET_FIND_USER_BODY = "USERS/RESET_FIND_USER_BODY";
export const USERS_SET_USERS = "USERS/SET_USERS";
export const USERS_SET_TOTAL_USERS_COUNT = "USERS/SET_TOTAL_USERS_COUNT";
export const USERS_SET_CURRENT_PAGE = "USERS/SET_CURRENT_PAGE";
export const USERS_SET_PAGE_COUNT = "USERS/SET_PAGE_COUNT";
export const PROFILE_CHANGE_USER_ID = "PROFILE/CHANGE_USER_ID";

export const IMAGES_CHANGE_FIND_IMAGES_BODY = "IMAGES/CHANGE_FIND_IMAGES_BODY";
export const IMAGES_RESET_FIND_IMAGES_BODY = "IMAGES/RESET_FIND_IMAGES_BODY";

export const MUSIC_CHANGE_FIND_MUSIC_BODY = "MUSIC/CHANGE_FIND_MUSIC_BODY";
export const MUSIC_RESET_FIND_MUSIC_BODY = "MUSIC/RESET_FIND_MUSIC_BODY";

export const VIDEOS_CHANGE_FIND_VIDEOS_BODY = "VIDEOS/CHANGE_FIND_VIDEOS_BODY";
export const VIDEOS_RESET_FIND_VIDEOS_BODY = "VIDEOS/RESET_FIND_VIDEOS_BODY";

export const DOCUMENTS_CHANGE_FIND_DOCUMENTS_BODY =
  "DOCUMENTS/CHANGE_FIND_DOCUMENTS_BODY";
export const DOCUMENTS_RESET_FIND_DOCUMENTS_BODY =
  "DOCUMENTS/RESET_FIND_DOCUMENTS_BODY";

export const FEEDS_CHANGE_FIND_FEEDS_BODY = "FEEDS/CHANGE_FIND_FEEDS_BODY";
export const FEEDS_RESET_FIND_FEEDS_BODY = "FEEDS/RESET_FIND_FEEDS_BODY";
